version: '3'

services:
   flaskapp:
     build: flask/
     container_name: flask
     volumes: 
       - '.:/workspace/dakoku_app'
     environment:
       TZ: Asia/Tokyo
     working_dir: '/workspace/dakoku_app/flask'
     expose:
       - '8000' 
     env_file:
       - .env
     networks:
       - flask_network
     command: gunicorn -c config.py
   
   nginx:
     build: 'nginx/'
     ports:
       - '8080:8080'
     depends_on:
       - flaskapp
     networks:
       - flask_network

   test:
     build: flask/
     container_name: test
     volumes:
       - '.:/workspace/dakoku_app'
     working_dir: '/workspace/dakoku_app/flask'
     environment:
       - FLASK_ENV=testing
     command: tail -f /dev/null
     networks:
       - flask_network
 

networks:
  flask_network:
    driver: bridge