version: '3'
services:
   flaskapp:
     build: flask/
     container_name: flask
     volumes: 
       - '.:/workspace/dakoku_app'
     environment:
       TZ: Asia/Tokyo
     working_dir: '/workspace/dakoku_app/flask'
     tty: true
     ports:
       - '8000:5000' 